<?php

namespace tjura\migration\commands;

use yii\console\Controller;

/**
 * @author  Tomasz Jura <jura.tomasz@gmail.com>
 */
class MigrateController extends Controller
{

    public function init()
    {
        die('aa');
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Big test
     * @return void
     */
    public function actionGenerate()
    {

    }

}
